/* Generated by Lucky Bingo Bot. Live verified player records for Admin Panel. */
"use strict";
window.LUCKY_BINGO_ADMIN = {
  "name": "sam",
  "username": "@samTesfa19",
  "phone": "+251939292694",
  "role": "Super administrator"
};
window.LUCKY_BINGO_PAYMENT_METHODS = {
  "Telebirr": {
    "name": "Telebirr",
    "account_name": "Lucky Bingo",
    "account_number": "0911 000 000",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  },
  "CBE Birr": {
    "name": "CBE Birr",
    "account_name": "Lucky Bingo CBE Birr",
    "account_number": "1000 000 000",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  },
  "M-Pesa": {
    "name": "M-Pesa",
    "account_name": "Lucky Bingo M-Pesa",
    "account_number": "0700 000 000",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  }
};
window.LUCKY_BINGO_PLAYERS = [
  {
    "id": "TG-551046010",
    "name": "@Hiwisha",
    "username": "@Ameneny",
    "email": "Ameneny@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 551046010)"
  },
  {
    "id": "TG-9236942755",
    "name": "Lucky Player",
    "username": "@Player_2755",
    "email": "Player_2755@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 9236942755)"
  },
  {
    "id": "TG-9992647139",
    "name": "Lucky Player",
    "username": "@Player_7139",
    "email": "Player_7139@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 9992647139)"
  },
  {
    "id": "TG-1110001",
    "name": "Lucky Player",
    "username": "@Player_Winner",
    "email": "Player_Winner@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 1110001)"
  },
  {
    "id": "TG-2220002",
    "name": "Lucky Player",
    "username": "@Player_Opponent",
    "email": "Player_Opponent@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 2220002)"
  },
  {
    "id": "TG-8892266325",
    "name": "Abel Tesfay",
    "username": "ID: 8892266325",
    "email": "8892266325@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 8892266325)"
  },
  {
    "id": "TG-987654321",
    "name": "Lucky Player",
    "username": "@Player_Test_Sync",
    "email": "Player_Test_Sync@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 987654321)"
  },
  {
    "id": "TG-9331970152",
    "name": "Lucky Player",
    "username": "@Player_0152",
    "email": "Player_0152@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 9331970152)"
  },
  {
    "id": "TG-765609989",
    "name": "Birhanu Gugsa💎",
    "username": "@Biregugsa",
    "email": "Biregugsa@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 765609989)"
  },
  {
    "id": "TG-9291219306",
    "name": "Lucky Player",
    "username": "@Player_9306",
    "email": "Player_9306@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 9291219306)"
  },
  {
    "id": "TG-9602653332",
    "name": "Lucky Player",
    "username": "@Player_3332",
    "email": "Player_3332@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 9602653332)"
  },
  {
    "id": "TG-9111111111",
    "name": "Lucky Player",
    "username": "@RemoteUser1",
    "email": "RemoteUser1@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 9111111111)"
  },
  {
    "id": "TG-8111222333",
    "name": "Lucky Player",
    "username": "@PhoneA_Player",
    "email": "PhoneA_Player@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 8111222333)"
  },
  {
    "id": "TG-8444555666",
    "name": "Lucky Player",
    "username": "@PhoneB_Player",
    "email": "PhoneB_Player@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 8444555666)"
  },
  {
    "id": "TG-1314310785",
    "name": "Gizachew Abay",
    "username": "@gizuye16",
    "email": "gizuye16@t.me",
    "phone": "+251918738918",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 1314310785)"
  },
  {
    "id": "TG-7453865545",
    "name": "Sura Sura",
    "username": "@Anj_mark1",
    "email": "Anj_mark1@t.me",
    "phone": "N/A",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 7453865545)"
  },
  {
    "id": "TG-7540599759",
    "name": "Br4",
    "username": "@abescd",
    "email": "abescd@t.me",
    "phone": "+251902544499",
    "balance": 0.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 7540599759)"
  }
];
