/* Generated by Lucky Bingo Bot. Live verified player records for Admin Panel. */
"use strict";
window.LUCKY_BINGO_ADMIN = {
  "name": "sam",
  "username": "@samTesfa19",
  "phone": "+251939292694",
  "role": "Super administrator"
};
window.LUCKY_BINGO_PAYMENT_METHODS = {
  "Telebirr": {
    "name": "Telebirr",
    "account_name": "Lucky Bingo",
    "account_number": "0911 000 000",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  },
  "CBE Birr": {
    "name": "CBE Birr",
    "account_name": "Lucky Bingo CBE Birr",
    "account_number": "1000 000 000",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  },
  "M-Pesa": {
    "name": "M-Pesa",
    "account_name": "Lucky Bingo M-Pesa",
    "account_number": "0700 000 000",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  }
};
window.LUCKY_BINGO_PLAYERS = [
  {
    "id": "TG-7540599759",
    "name": "Br4",
    "username": "@abescd",
    "email": "abescd@t.me",
    "phone": "+251902544499",
    "balance": 50.0,
    "games": 0,
    "lastActive": "Just now",
    "status": "active",
    "avatar": "blue",
    "note": "Telegram Verified Player (TG ID: 7540599759)"
  }
];
